# Generated by Django 2.2.3 on 2019-07-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='URL',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content2',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='date',
        ),
        migrations.AddField(
            model_name='post',
            name='belong',
            field=models.TextField(blank=True, null=True),
        ),
    ]
