# Generated by Django 2.2.3 on 2019-07-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20190705_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='kind',
            field=models.CharField(choices=[('a', 'Administration'), ('b', 'Economy'), ('c', 'Engineering'), ('d', 'Art')], default='Administration', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='URL',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='belong',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
