# Generated by Django 2.2.3 on 2019-07-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='kind',
            field=models.CharField(choices=[('Administration', 'Administration'), ('Economy', 'Economy'), ('Engineering', 'Engineering'), ('Art', 'Art')], default='Administration', max_length=100),
        ),
    ]
